spring:
 application:
  name: Config-Default
eureka:
  instance:
   prefer-ip-address: true
  client:
    fetchRegistry: false
    registerWithEureka: false
    service-url:
      defaultZone: http://localhost:8080/eureka
  
      
      
      
